# Generated by Django 4.2.26 on 2025-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_item_category_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.CharField(default='Daily', max_length=200),
        ),
    ]
