# Generated by Django 4.2.26 on 2025-12-11 04:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_tobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
